export default {
    form_col: 'Datastr',
    formDescription_col: 'Form',
    field_col: 'Field Name',
    fieldDescription_col: 'Field',
    status_col: 'Query Status',
    status_order: ['Open', 'Answered', 'Closed', 'Cancelled'],
    status_colors: ['#fb9a99', '#fdbf6f', '#1f78b4', 'gray'],
    aging_col: 'Query Age Category',
    aging_order: null,
    aging_colors: ['#fcae91', '#fb6a4a', '#de2d26', '#a50f15'],
    groups: null,
    status_groups: null,
    site_col: 'Site Name',
    filters: null,
    details: null,
    cutoff: 10,
    alphabetize: false,
    exportable: true,
    nRowsPerPage: 10
};
